# -*- coding: utf-8 -*-
"""Person detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ls4qeXNrGlNFtYSHZiff7iyUnqzN7QUw
"""

from google.colab import drive
drive.mount('/content/gdrive')

import os

!git clone https://github.com/AlexeyAB/darknet

!unzip /content/gdrive/MyDrive/Person_dataset/Train.zip -d /content/darknet/data/train



!echo -e 'classes=2\n train=/content/darknet/data/train.txt\n valid=/content/darknet/data/test.txt\n names=/content/darknet/data/classes.names\n backup=/content/gdrive/MyDrive/backupp'>/content/darknet/data/image_data.data

!echo -e 'person\nperson-like' > /content/darknet/data/classes.names

import glob
images_list=glob.glob('/content/darknet/data/train/Train/Images/*.jpg')

images_list_test=images_list[:int(len(images_list)*0.02)]
images_list=images_list[int(len(images_list)*0.02):]

with open('/content/darknet/data/train.txt','w') as f:
  f.write('\n'.join(images_list))

with open('/content/darknet/data/test.txt','w') as f:
  f.write('\n'.join(images_list_test))

os.chdir('/content/darknet')
!make



!./darknet

!cp /content/darknet/cfg/yolov4.cfg /content/darknet/cfg/yolov4-train.cfg

!cp /content/darknet/cfg/yolov4.cfg /content/darknet/cfg/yolov4-test.cfg

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137



!./darknet detector train data/image_data.data cfg/yolov4-train.cfg yolov4.conv.137 -dont_show



!./darknet detector train data/image_data.data cfg/yolov4-train.cfg /content/gdrive/MyDrive/backupp/yolov4-train_last.weights -dont_show

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet

!./darknet detector test data/image_data.data cfg/yolov4-train.cfg /content/gdrive/MyDrive/Backup/yolov4-train_final.weights -ext_output -dont_show -out result.txt < data/train.txt